version: "3.9"

services:
  root_db:
    image: postgres:16
    container_name: root_db
    environment:
      POSTGRES_DB: PTHSP_backup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"        # expose ra ngoài nếu cần
    volumes:
      - root_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  vector_db:
    image: postgres:16
    container_name: vector_db
    environment:
      POSTGRES_DB: vectorDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - vector_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #     - ./ollama-entrypoint.sh:/usr/local/bin/ollama-entrypoint.sh
  #   entrypoint: ["/usr/local/bin/ollama-entrypoint.sh"]
  #   restart: unless-stopped

  app:
    build:
      context: .
    container_name: rag_vector_app
    depends_on:
      - root_db
      - vector_db
      # - ollama
    command: ["python", "-m", "app.main"]
    volumes:
      - ./:/app
    restart: unless-stopped

volumes:
  root_db_data:
  vector_db_data:
  # ollama_data: